### ISSUE TITLE
Parsing a `<table>` adds an additional `<tbody>`

### ISSUE THREAD

**Issue by marcoroth** [flavorjones/nokogiri-html5-inference#1]
**Code:**
```ruby
Nokogiri::HTML5::Inference.parse("<table><tr><th>1</td><th>2</th></tr></table>").to_html
```

**Output:**
```html
<table><tbody><tr><th>1</th><th>2</th></tr></tbody></table>
```

**Expected output:**
```html
<table><tr><th>1</td><th>2</th></tr></table>
```

**Comment by marcoroth** [comment]
Similarly: 

**Code:**
```ruby
Nokogiri::HTML5::Inference.parse("<template><table><tr></tr></table></template>").to_html
```

**Output:**
```html
<template><table><tbody><tr></tr></tbody></table></template>
```

**Expected output:**
```html
<template><table><tr></tr></tbody></template>
```

**Comment by flavorjones** [comment]
This is the behavior of the HTML5 spec and is correct. See https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable

> A start tag whose tag name is one of: "td", "th", "tr"
> - [Clear the stack back to a table context](https://html.spec.whatwg.org/multipage/parsing.html#clear-the-stack-back-to-a-table-context). (See below.)
> - **[Insert an HTML element](https://html.spec.whatwg.org/multipage/parsing.html#insert-an-html-element) for a "tbody" start tag token with no attributes**, then switch the [insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#insertion-mode) to "[in table body](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intbody)".
> - Reprocess the current token.

(emphasis mine)

**Comment by flavorjones** [comment]
Can you say more about why you expect there to be no `tbody` tag? What does this tag's presence break for you?

**Comment by marcoroth** [comment]
Nvm, I just realized this is also the case for the regular `Nokogiri::HTML5::DocumentFragment`:

```ruby
irb(main):003> Nokogiri::HTML5::DocumentFragment.parse("<table><tr><th>1</th><th>2</th></tr></table>").to_html

=> "<table><tbody><tr><th>1</th><th>2</th></tr></tbody></table>"
```

Luckily, I don't think the tag's presence breaks anything in my case, it was more kind of an unexpected behavior. Let's close this then 👍🏼

**Comment by flavorjones** [comment]
I want to just point out that on a few occasions I've heard something like, "that's unexpected behavior" about the HTML5 spec from either you or other folks ...

Is there something I could be doing to better highlight that much of this behavior does not come from Nokogiri's maintainers making arbitrary decisions but from the WHATWG and the HTML5 specification?

**Comment by marcoroth** [comment]
Yeah good point. I'm not entirely sure where that mindset is coming from. 

I guess a lot has to do with the assumption that a "parser" usually only returns a representation of the snippet you gave it. In this case, and other similar cases, you get a few "unexpected" additional nodes in your parse result.

But yeah, looking from the HTML5 spec point of view, this totally makes sense and isn't "unexpected".
