### ISSUE TITLE
Using a `template` context element

### ISSUE THREAD

**Issue by stevecheckoway** [flavorjones/nokogiri-html5-inference#2]
As mentioned in https://github.com/sparklemotion/nokogiri/issues/3023#issuecomment-2076077730, I tested parsing using a `template` as the context node in all cases. This does not work when the fragment contains a `head` or `body` tag but appears to work in every other case.

Specifically, after
```diff
diff --git a/lib/nokogiri/html5/inference.rb b/lib/nokogiri/html5/inference.rb
index e501e01..942089d 100644
--- a/lib/nokogiri/html5/inference.rb
+++ b/lib/nokogiri/html5/inference.rb
@@ -132,12 +132,7 @@ else
             if context.nil?
               Nokogiri::HTML5::Document.parse(input)
             else
-              fragment = Nokogiri::HTML5::DocumentFragment.new(Nokogiri::HTML5::Document.new, input, context)
-              if pluck && (path = pluck_path(input))
-                fragment.xpath(path)
-              else
-                fragment
-              end
+              Nokogiri::HTML5::DocumentFragment.new(Nokogiri::HTML5::Document.new, input, 'template')
             end
           end
```
all of the tests pass except for 3: 
```
Run options: --seed 37366

# Running:

...........FFF.............

Finished in 0.013474s, 2003.8593 runs/s, 3562.4165 assertions/s.

  1) Failure:
Nokogiri::HTML5::Inference::.parse::passed a fragment requiring 'in html' insertion mode#test_0001_parses '<body><div>hello</div></body>' correctly [test/nokogiri/html5/test_inference.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-"<body><div>hello</div></body>"
+"<div>hello</div>"


  2) Failure:
Nokogiri::HTML5::Inference::.parse::passed a fragment requiring 'in html' insertion mode#test_0002_parses '<head><meta charset="UTF-8"><title>hello</title></head>' correctly [test/nokogiri/html5/test_inference.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-"<head><meta charset=\"UTF-8\"><title>hello</title></head>"
+"<meta charset=\"UTF-8\"><title>hello</title>"


  3) Failure:
Nokogiri::HTML5::Inference::.parse::multiple children that need plucking::with pluck: false#test_0001_includes the intermediate nodes created [test/nokogiri/html5/test_inference.rb:116]:
--- expected
+++ actual
@@ -1 +1 @@
-"<tbody><tr><td>hello</td></tr><tr><td>world</td></tr></tbody>"
+"<tr><td>hello</td></tr><tr><td>world</td></tr>"


27 runs, 48 assertions, 3 failures, 0 errors, 0 skips
```

Unfortunately, parsing a fragment containing a `head` element in the context of `html` also produces an empty `body` element. Similarly, parsing a fragment containing a `body` element in the context of `html` also produces an empty `head`.

This behavior actually exposes a bug in the current implementation of `Inference::parse`. These tests should pass, but they fail.
```diff
diff --git a/test/nokogiri/html5/test_inference.rb b/test/nokogiri/html5/test_inference.rb
index 2f00898..2fd9e4f 100644
--- a/test/nokogiri/html5/test_inference.rb
+++ b/test/nokogiri/html5/test_inference.rb
@@ -99,6 +99,25 @@ describe Nokogiri::HTML5::Inference do
       end
     end

+    describe "passed a Fragment containing head and body" do
+      it "returns a Fragment containing both head and body" do
+        fragment = "<head></head><body></body>"
+        actual = Nokogiri::HTML5::Inference.parse(fragment).to_html
+
+        assert_equal(fragment, actual)
+      end
+    end
+
+    describe "passed a Fragment containing head and p" do
+      it "returns a Fragment containing both head and body" do
+        fragment = "<head><p>"
+        expected = "<head></head><body><p></p></body>"
+        actual = Nokogiri::HTML5::Inference.parse(fragment).to_html
+
+        assert_equal(expected, actual)
+      end
+    end
+
     describe "multiple children that need plucking" do
       it "parses correctly" do
         fragment = "<tr><td>hello</td></tr><tr><td>world</td></tr>"
```

My inclination is to say that this is a bug in the HTML standard which should allow `head` and `body` elements to appear inside a `template`. A quick test shows that Firefox follows the standard as written and disallows that.

**Comment by flavorjones** [comment]
@stevecheckoway I think the two tests you added above will pass once #4 is merged -- this was a bad design decision on my part. In fact I just added the tests to that PR and they're green.

**Comment by marcoroth** [comment]
I think we can close this too, since #4 was merged and released in `v0.2.0` 👍🏼

**Comment by flavorjones** [comment]
Hmm, I think this is worth exploring a bit more because the proper use of a `<template>` tag will avoid creating intermediate parents ...

**Comment by stevecheckoway** [comment]
One option would be to default to using `template` as the context node in Nokogiri as I suspect most people who parse fragments want that behavior. But that would be a breaking change. (And even if that were desirable, we'd probably want to make sure https://github.com/sparklemotion/nokogiri/issues/3183 is handled first to make specifying the context easier.)

That said, it wouldn't help with the `head`/`body` issues so I suspect a plucking via XPath approach is still required for those.

**Comment by flavorjones** [comment]
See https://github.com/flavorjones/nokogiri-html5-inference/pull/7 for the exciting conclusion

**Comment by flavorjones** [comment]
> One option would be to default to using template as the context node in Nokogiri as I suspect most people who parse fragments want that behavior

Yes! Definitely.

> But that would be a breaking change.

Also unfortunately true, but I think we can make the argument that the new behavior is arguably more correct and get away with it (with the escape hatch described at 3183 as you mentioned).
