### ISSUE TITLE
Parsing a `<head>` next to a `<body>` tags strips the `<body>` tag

### ISSUE THREAD

**Issue by marcoroth** [flavorjones/nokogiri-html5-inference#3]
**Code:**
```ruby
Nokogiri::HTML5::Inference.parse("<head></head> <body></body>").to_html
```

**Output:**
```html
<head></head>
```

**Expected output:**
```html
<head></head> <body></body>
```

**Comment by marcoroth** [comment]
Just wanted to bring this up here, maybe the answer here is: "this works as designed" and that would be fine too

**Comment by flavorjones** [comment]
See https://github.com/flavorjones/nokogiri-html5-inference/pull/4 !
