### ISSUE TITLE
Parsing `<head>` fragment adds `<body>` tag

### ISSUE THREAD

**Issue by marcoroth** [flavorjones/nokogiri-html5-inference#5]
Just bumped `nokogiri-html5-inference` to `0.2.0` in my project and now got a, previously passing, failing test:

**Code:**
```ruby
Nokogiri::HTML5::Inference.parse(%(<head></head>)).to_html
```

**Output:**
```html
<head></head><body></body>
```

**Expected output:**
```html
<head></head>
```

I guess this makes sense as a side-effect of #4. I don't think it would break anything in my case, but wanted to bring it up nonetheless.

**Comment by marcoroth** [comment]
I would expect this test case to pass:
```ruby
    describe "passed a Fragment containing head" do
       it "returns a Fragment containing head" do
         fragment = "<head></head>"
         actual = Nokogiri::HTML5::Inference.parse(fragment).to_html

         assert_equal(fragment, actual)
       end
     end
```

**Comment by marcoroth** [comment]
In contrast, it works as expected with only the `<body>` tag:

```ruby
Nokogiri::HTML5::Inference.parse(%(<body></body>)).to_html
=> "<body></body>"
```

**Comment by flavorjones** [comment]
What's the exact rule you want here? In #3 you said the expected output is `<head></head> <body></body>` and in this you're saying the expected output is `<head></head>` for basically the same parsed fragment.

I can either always include `body` or I can optionally remove an empty `body` ... but I don't want to complicate the code too much here to handle what's surely an edge case?

**Comment by marcoroth** [comment]
I guess what I expected was something like:

| Input | Expected | Actual (on v0.2.0) |
| --- | --- | --- |
| `<html></html>` | `<html></html>` | `<html><head></head><body></body></html>` |
| `<head></head>` | `<head></head>` | `<head></head><body></body>` |
| `<body></body>` | `<body></body>` | `<body></body>` |
| `<head></head><body></body>` | `<head></head><body></body>` | `<head></head><body></body>` |
| `<html><head></head><body></body></html>` | `<html><head></head><body></body></html>` | `<html><head></head><body></body></html>` |

But yeah, it's only the first two examples that are different. And, after some reflection I think it's not really breaking anything. I'm happy to close this too then 👍🏼
