### ISSUE TITLE
Parsing sole `<html>` tag adds `<head>` and `<body>` tags

### ISSUE THREAD

**Issue by marcoroth** [flavorjones/nokogiri-html5-inference#6]
**Code:**
```ruby
Nokogiri::HTML5::Inference.parse(%(<html></html>)).to_html
```

**Output:**
```html
<html><head></head><body></body></html>
```

**Expected output:**
```html
<html></html>
```

**Comment by flavorjones** [comment]
What's the use case here? Surely if an `html` tag is present there will be either head or body tags in it, no? What's the purpose of returning an empty `html` tag?

**Comment by marcoroth** [comment]
Yeah, good point. I was trying to plug in `nokogiri-html5-inference` into phlexing (https://github.com/marcoroth/phlexing/pull/337) and had a failing test.

In this case I was just converting a `<html></html>` tag and wanted to get back the equivalent in Phlex syntax. In this case it gave me:

```ruby
html do
  head

  body
end
```

which might be just fine, but "unexpected" because it's technically more than what was given. Maybe I should just update the assertions and move on, as it's not really breaking anything.

**Comment by flavorjones** [comment]
OK, I'm going to close this, then. I'm happy to revisit if there's some real-world use case that this is making difficult!

**Comment by marcoroth** [comment]
Totally fair, I'm going to update the assertions 👍🏼
